### ISSUE TITLE
Getting Error while calling analyze method on application that has Iframes, java.lang.RuntimeException: Error when removing sandbox from iframes with Selenium with java

### ISSUE THREAD

**Issue by lakshminagandla** [TroyWalshProf/AccessibilityDemo#1]
Software dependency versions used:

com.deque.html.axe-core : 4.0.0

Calling methods:

When we call the method : Results result = builder.withoutIframeSandboxes().analyze(driver)

and

Results result = builder.analyze(driver)

Error that we are getting:

"java.lang.RuntimeException: Error when removing sandbox from iframes"

Note: For few of the other applications, the Analyzer method is working as expected. But on few applications, throwing above exception message.

Can any one please check share what exactly issue with AXE or application side?

Code that I have used: 

UserDetailsPage detailsPage = new UserDetailsPage(driver, webSite, extentedReport).get();

			File file = new File("src/main/resources/axe.min.js");
			
			String path = file.getCanonicalPath();
			
			AxeBuilder builder = new AxeBuilder();
			 
			String timeoutFilePath = "src/main/resources/axe.min.js";
			 
			FileAxeScriptProvider axeScriptProvider = new FileAxeScriptProvider(timeoutFilePath);
			 
			builder.setAxeScriptProvider(axeScriptProvider);
			 
			Results result = builder.analyze(driver);
			 
			List<Rule> violations = result.getViolations();
			 
			Assert.assertEquals(0, violations.size(), "No violations found");

**Comment by TroyWalshProf** [comment]
@LakshmiNagandla - 
This is not an issue I can fix in this project.  

Here is where you likely what to post this bug:
https://github.com/dequelabs/axe-core-maven-html
